[project]
name = "gdq-cli"
version = "1.2"
requires-python = ">=3.12"
dependencies = [
  "phoenix-channels-python-client",
  "requests",
  "xdg",
]

[project.scripts]
bus = "bus.__main__:main"
gdq = "gdq.__main__:main"

[dependency-groups]
test = [
  "pytest",
  "pytest-cov",
]

[build-system]
requires = ["uv_build>=0.12.23,<0.13"]
build-backend = "uv_build"

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
fix = true
line-length = 120
builtins = ["__"]
target-version = "py314"

[tool.ruff.lint]
ignore = ["ANN", "D", "T201"]
select = ["ALL"]

[tool.ruff.lint.flake8-copyright]
min-file-size = 1

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "PLR2004"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
bus = ["*.json"]

[tool.ty]

[tool.uv]
default-groups = ["test"]

[tool.uv.build-backend]
module-name = ["bus", "gdq"]
